# Generated by Django 3.2.13 on 2022-06-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=2)),
                ('coord_lat', models.FloatField()),
                ('coord_lon', models.FloatField()),
            ],
        ),
    ]
